apiVersion: v1
kind: Service
metadata:
  name: loki-service
spec:
  type: LoadBalancer
  selector:
    app: loki
  ports:
    - port: 3100
      protocol: TCP
      targetPort: 3100
      name: loki-port
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: grafana-port

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
spec:
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.9.6
          ports:
            - containerPort: 3100
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: "admin"
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin"
          volumeMounts:
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
              readOnly: true
      volumes:
        - name: grafana-datasources
          configMap:
            name: grafana-datasources

---

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-service:3100