apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:latest
          ports:
            - containerPort: 9091
          command:
            - "/opt/keycloak/bin/kc.sh"
            - "--verbose"
            - "start-dev"
            - "--import-realm"
            - "--http-port=9091"
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
          volumeMounts:
            - name: vertx-cache
              mountPath: /tmp/vertx-cache
            - name: keycloak-import
              mountPath: /opt/keycloak/data/import
      volumes:
        - name: vertx-cache
          emptyDir: {}
        - name: keycloak-data
          emptyDir: {}
        - name: keycloak-import
          configMap:
            name: keycloak-realm-config
            items:
              - key: realm.json
                path: realm-export.json
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
  type: LoadBalancer

