apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-redlog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-redlog
  template:
    metadata:
      labels:
        app: mongo-redlog
    spec:
      containers:
        - name: mongo-redlog
          image: mongo:5
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: toor
            - name: MONGO_INITDB_DATABASE
              value: admin
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
            - name: mongo-init-script
              mountPath: /docker-entrypoint-initdb.d/
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc
        - name: mongo-init-script
          configMap:
            name: mongo-init-script
