apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-script
data:
  mongo-init.js: |
    db.createUser({
        user: 'user',
        pwd: 'pass',
        roles: [{role: 'dbOwner', db: 'redlog'}]
    });
